In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [3]:
data=pd.read_csv('./train.csv')

In [4]:
sampleData=data.sample(10000)

In [5]:
sampleData.shape

(10000, 24)

In [6]:
sampleData.head(20)

id  click      hour    C1  banner_pos   site_id  \
13850333  3.033463e+18      0  14102404  1005           0  1fbe01fe   
7210101   1.342870e+19      0  14102212  1005           0  fec6e632   
38422661  1.505207e+19      0  14103012  1005           1  57ef2c87   
6166149   5.006787e+18      0  14102209  1005           0  85f751fd   
2005352   4.434557e+18      0  14102109  1005           0  1fbe01fe   
36531293  1.599741e+19      0  14103003  1005           0  dcc019de   
32598910  1.043974e+19      1  14102902  1005           1  b7e9786d   
28081369  9.783225e+18      1  14102806  1005           1  88154ade   
9805055   1.050270e+19      0  14102303  1005           0  1fbe01fe   
26288880  5.891523e+18      0  14102717  1005           0  85f751fd   
13573881  2.196933e+18      0  14102402  1005           1  d9750ee7   
18935941  9.686654e+18      0  14102515  1005           0  85f751fd   
26104060  9.198949e+18      1  14102716  1005           1  b7e9786d   
23691317  8.324410e+18      0  14102621  1005           0  5b08c53b   
27508272  1.802659e+19      0  14102803  1005           0  addf1d39   
22824084  7.088608e+18      1  14102615  1005           0  38217daf   
37336826  5.072776e+18      0  14103006  1005           1  b7e9786d   
2887654   2.464093e+18      1  14102114  1005           0  9a977531   
10905075  2.227170e+18      0  14102308  1005           1  85f751fd   
30654563  1.772151e+19      0  14102815  1005           0  d9750ee7   

         site_domain site_category    app_id app_domain ...  device_type  \
13850333    f3845767      28905ebd  ecad2386   7801e8d9 ...            1   
7210101     ace5b8fd      3e814130  ecad2386   7801e8d9 ...            1   
38422661    bd6d812f      f028772b  ecad2386   7801e8d9 ...            1   
6166149     c4e18dd6      50e219e0  e96773f0   2347f47a ...            1   
2005352     f3845767      28905ebd  ecad2386   7801e8d9 ...            1   
36531293    250469f8      3e814130  ecad2386   7801e8d9 ...            1   
32598910    b12b9f85      f028772b  ecad2386   7801e8d9 ...            1   
28081369    9f448720      3e814130  ecad2386   7801e8d9 ...            1   
9805055     f3845767      28905ebd  ecad2386   7801e8d9 ...            1   
26288880    c4e18dd6      50e219e0  92f5800b   ae637522 ...            1   
13573881    98572c79      f028772b  ecad2386   7801e8d9 ...            1   
18935941    c4e18dd6      50e219e0  92f5800b   ae637522 ...            1   
26104060    b12b9f85      f028772b  ecad2386   7801e8d9 ...            1   
23691317    7687a86e      3e814130  ecad2386   7801e8d9 ...            1   
27508272    db11867b      f028772b  ecad2386   7801e8d9 ...            1   
22824084    449497bc      f028772b  ecad2386   7801e8d9 ...            1   
37336826    b12b9f85      f028772b  ecad2386   7801e8d9 ...            1   
2887654     a434fa42      f028772b  ecad2386   7801e8d9 ...            1   
10905075    c4e18dd6      50e219e0  13684a79   2347f47a ...            1   
30654563    98572c79      f028772b  ecad2386   7801e8d9 ...            1   

         device_conn_type    C14  C15  C16   C17  C18   C19     C20  C21  
13850333                0  15701  320   50  1722    0    35      -1   79  
7210101                 0  20366  320   50  2333    0    39      -1  157  
38422661                0  22680  320   50  2528    0   167  100079  221  
6166149                 0  21768  320   50  2506    0    35      -1  157  
2005352                 2  21757  320   50  2502    0    35      -1  221  
36531293                0  23723  320   50  2716    3    47      -1   23  
32598910                0  22681  320   50  2528    0    39  100075  221  
28081369                0  22683  320   50  2528    0    39  100081  221  
9805055                 0  15708  320   50  1722    0    35  100084   79  
26288880                3  21191  320   50  2424    1   161  100189   71  
13573881                0  17062  320   50  1939    2  1063      -1  117  
18935941                3  2119

In [7]:
sampleData.shape

(10000, 24)

In [8]:
sampleData.shape

(10000, 24)

In [9]:
y=sampleData['click']

In [18]:
y.head()

13850333    0
7210101     0
38422661    0
6166149     0
2005352     0
Name: click, dtype: int64

In [19]:
y.shape

(10000,)

In [20]:
features=['hour','C1','banner_pos','device_type','device_conn_type','C14','C15','C16','C17','C18','C19','C20','C21']

In [21]:
x=sampleData[features]

In [22]:
x.shape

(10000, 13)

In [23]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=324)

Decision TRees

In [48]:
my_classifier=DecisionTreeClassifier(max_leaf_nodes=2 , random_state=0)
my_classifier.fit(x_train,y_train)
predictions=my_classifier.predict(x_test)
accuracy_score(y_true=y_test,y_pred=predictions)

0.83363636363636362

KNN


In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [26]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2587,  164],
       [ 502,   47]])

In [31]:
accuracy_score(y_true=y_test,y_pred=y_pred)

0.79818181818181821

SVM

In [34]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred2 = classifier.predict(x_test)
accuracy_score(y_true=y_test,y_pred=y_pred2)

0.83363636363636362

Naive Bayes


In [36]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
accuracy_score(y_true=y_test,y_pred=y_pred)

0.7627272727272727

Random Forest

In [41]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x, y)

# Predicting a new result
y_pred3 = classifier.predict(x_test)
accuracy_score(y_true=y_test,y_pred=y_pred3)

0.7627272727272727

In [ ]:
Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)
accuracy_score(y_true=y_test,y_pred=y_pred)

0.83333333333333337

In [65]:
type(my_classifier)

sklearn.tree.tree.DecisionTreeClassifier

In [67]:
predictions[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
y[0:10]

8061116     1
1567686     0
24362698    1
32798557    0
33249878    0
18953849    0
16461641    0
11643928    0
10780252    0
33096970    0
Name: click, dtype: int64

In [70]:
accuracy_score(y_true=y_test,y_pred=predictions)

0.82454545454545458

In [71]:
lr=LogisticRegression()

NameError: name 'LogisticRegression' is not defined

In [72]:
from sklearn.linear_model import LogisticRegression


In [81]:
logistic = LogisticRegression()
logistic.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [86]:
pred[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
accuracy_score(y_true=y_test,y_pred=pred)

NameError: name 'pred' is not defined